### ISSUE TITLE
Mark notification as read

### ISSUE THREAD

**Issue by eriksoon** [part-up/app#103]
I would like to be able to mark the notification as read (although I didn't read it by going to the page). I would like this, because I'm often partner in a part-up just for one or two activities and do not want to welcome every new supporter or read every update on activities that do not apply to me. Eg: I would like to close/mark it as read by swiping.

**Comment by ralphboeije** [comment]
Why do you want to do anything with the notifications at all? Do you feel obliged to, or stressed in some way by seeing them?

**Comment by ralphboeije** [comment]
closed this one because of Part-up2.0 development. notifications will be changed.
