### ISSUE TITLE
Opening a chat from push notification freezes the app

### ISSUE THREAD

**Issue by ralphboeije** [part-up/app#110]
Since 1.4.1 I often experience that when opening the app from a chat push notification, the app freezes. One example is below: the header text of chat and notifications are on top of each other. Other examples are: app opens on chat tab, but doesn't load the new item. On tap on notification tab icon, it is highligted as active, but chat tab content remains visible.

Sometimes the app loads the right content after a couple of seconds, but most of the time I have to kill the app and relaunch it.

![img_4714](https://cloud.githubusercontent.com/assets/14044235/17212033/ed3a0f1a-54cc-11e6-91f2-767bd74638eb.PNG)

**Comment by ralphboeije** [comment]
maybe has to do with broken session?

**Comment by jessedvrs** [comment]
It has to do with broken data. Could be fixed as I made the code more forgiving to data. Let me know if the problem still occurs after the next release.
