### ISSUE TITLE
Remove archived tribes from tribes view

### ISSUE THREAD

**Issue by ralphboeije** [part-up/app#111]
In the part-up repo release, tribes can have archived state. They should be filtered in the app tribe tab also.

**Comment by jessedvrs** [comment]
This was never the case.

**Comment by ralphboeije** [comment]
@jessedvrs Yes, it was and still is, see screenshot. Both in tribes tab and in tribe chat I see archived tribes.
![img_4904](https://cloud.githubusercontent.com/assets/14044235/18289892/9bf0a658-7481-11e6-96d4-5c930955424d.PNG)

**Comment by jessedvrs** [comment]
Oh I thought you meant the grayed-out tribes (with missing name and image). Sorry! Will take a look at this.

**Comment by jessedvrs** [comment]
Was server issue.
Fixed in part-up/part-up repo in branch *feat-chat-improvements-for-app*
