### ISSUE TITLE
Part-up app has data retrieving issues on iOS10

### ISSUE THREAD

**Issue by peterpeerdeman** [part-up/app#119]
The partup app does not work properly on iOS10, both the old version 1.4.* and 1.5.*. Users are able to login but cannot acquire data properly, which results in empty screens and hanging transitions.

It seems the compatibility issues are known issues in the community, please see this thread for discussions on an updated version of meteor cordova plugin that has to be used to solve some issues

https://forums.meteor.com/t/ios-10-compatibility/26065/35

actionplan is to create an environment with proper version of xcode / ios build tools, create a build of part-up app, test it on iOS10 and apply the new meteor cordova plugin and see if it solves the problems.

**Comment by andreleon** [comment]
These are the two most important steps I took to make the app work on iOS 10

1. I upgraded the app's Meteor version to **1.4.2-beta.4** wich re-enables websocket capabilities to a cordova app on iOS 10 when you **add `<meta http-equiv="Content-Security-Policy" content="default-src * 'self' data: blob: 'unsafe-inline' 'unsafe-eval' ws://* wss://* ">` to the project `<head>`**
2. I added the cordova plugin `cordova-plugin-meteor-webapp@https://github.com/meteor/cordova-plugin-meteor-webapp.git#8bf95eed3f313299fc2de33658866278eea2cdc5` to prevent Xcode 8 from making any changes to the cordova Swift code when compiling it to **Swift version 3**.
