### ISSUE TITLE
Receiving a notification on the Testflight app on IOS10 breaks the app

### ISSUE THREAD

**Issue by ralphboeije** [part-up/app#121]
As seen and reproduced today @lifely office.

**Comment by ralphboeije** [comment]
@andreleon in my app it magically works again. Can you check if it works with you? It might have been a specific notification that breaks it? really strange.

**Comment by ralphboeije** [comment]
@andreleon today the app magically stopped working again. The only way to use it, is when you force touch on the app icon and choose chat.

**Comment by andreleon** [comment]
Update: I managed to capture this error
<img width="1191" alt="screen shot 2016-10-12 at 14 52 55" src="https://cloud.githubusercontent.com/assets/1391492/19310713/bba023c2-908b-11e6-8ab0-27d119012280.png">

**Comment by andreleon** [comment]
I found the problem, iOS 10 works fine, it's the part-up-js-models npm module that causes these issues.

**Comment by andreleon** [comment]
In commit 8569895042b9d021fe06d7590eed021d0d2fddb2 I did some refactoring on the notifications model to make it forgiving for future new notifications

**Comment by ralphboeije** [comment]
Great!! So it has nothing to do with the app itself? Let's release that one immediately then.

**Comment by andreleon** [comment]
no!!

**Comment by andreleon** [comment]
The app has to be re-packaged with the new version of part-up-js-models
