### ISSUE TITLE
App - Part-up update detail message reply

### ISSUE THREAD

**Issue by peterpeerdeman** [part-up/app#13]
<a href="https://github.com/peterpeerdeman"><img src="https://avatars.githubusercontent.com/u/685599?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [peterpeerdeman](https://github.com/peterpeerdeman)**
_Monday Apr 11, 2016 at 12:43 GMT_
_Originally opened as https://github.com/part-up/part-up/issues/365_

----

As an app user I want to be able to reply with a comment on an update

https://redpen.io/zvbf0b7f6a00b0ad92

**Comment by ralphboeije** [comment]
Test findings: 
1. "@replies" are not rendered properly. 
2. When clicking "done" on the native keyboard the send button doesn't get triggered

**Comment by jessedvrs** [comment]
1. Still? After the 1.0.0 release?
2. Yep noticed. We'll probably fix it in the upcoming sprint.

**Comment by peterpeerdeman** [comment]
moved issue to new "login flow optimization" story
