### ISSUE TITLE
App - Part-ups (Partner)

### ISSUE THREAD

**Issue by peterpeerdeman** [part-up/app#14]
<a href="https://github.com/peterpeerdeman"><img src="https://avatars.githubusercontent.com/u/685599?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [peterpeerdeman](https://github.com/peterpeerdeman)**
_Monday Apr 11, 2016 at 12:44 GMT_
_Originally opened as https://github.com/part-up/part-up/issues/366_

----

As an app user, I want to see the part-ups where I am a partner, including the picture, partup title and number of unread updates on that partup

https://redpen.io/ux1145f86d36981e01

**Comment by ralphboeije** [comment]
Test finding: loading time is really long if you have a lot of part-ups like I do. It is also this way on the web, but for the native feeling this is killing in the app. Suggestions: make it two api calls, one for partner and one for supporter part-ups, because the partner part-ups are only visible on first load.

**Comment by jessedvrs** [comment]
On which app version do you have these findings?

**Comment by ralphboeije** [comment]
iOS 1.0.0 version. Added this based on the previous version, but rechecked in the current version.

**Comment by jessedvrs** [comment]
Okay. I asked, because I've build in a cache system for Part-ups and Tribes since version 1.0.0. Could you re-check?

**Comment by ralphboeije** [comment]
I did the recheck. The load time has definitely improved since the previous version. However, it is still somewhat slow. I think cutting the API call in two could improve it to a desired level!?

**Comment by wouterd** [comment]
How about using a JSON Stream so you can show the part-ups as they stream in? I've got good experiences with that f.ex with logging applications.

**Comment by jessedvrs** [comment]
To be able to focus on feature development, I did not yet build in any call optimisations or paging (except the limit of 35 notifications). In the upcoming sprint we'll build in paging (aka infinite scroll) on part-ups and tribes pages.
