### ISSUE TITLE
App - Tribes

### ISSUE THREAD

**Issue by peterpeerdeman** [part-up/app#16]
<a href="https://github.com/peterpeerdeman"><img src="https://avatars.githubusercontent.com/u/685599?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [peterpeerdeman](https://github.com/peterpeerdeman)**
_Monday Apr 11, 2016 at 12:46 GMT_
_Originally opened as https://github.com/part-up/part-up/issues/368_

----

As an app user I want to be able to view my tribes, including a picture and tribe name.

When clicking on a tribe, the in-app browser will be opened showing that tribe in the web application

https://redpen.io/db44ba5eb2e8f89ff0

**Comment by peterpeerdeman** [comment]
feedback: this page seems to not work with @ralphboeije his account, we should try to reproduce this case by logging in as ralph through acceptance server.

**Comment by jessedvrs** [comment]
@ralphboeije I suppose it's working for you again?

**Comment by ralphboeije** [comment]
@jessedvrs no this is not working for me. I have only seen it working once, but never again. Even when I wait for a long time they don't appear.
