### ISSUE TITLE
Scroll back on comment not working

### ISSUE THREAD

**Issue by ralphboeije** [part-up/app#30]
When I add a comment that is longer that the input field, there is no way for me to get back to the first part of the comment. In other apps I would tap and hold and then be able to move to the left of the comment input field and then see the text scroll back to the beginning.

https://part-up.uservoice.com/assets/102116574/IMG_2005.PNG

OS: iOS 9.3.2 
App version: 1.0.2

**Comment by peterpeerdeman** [comment]
was fixed when implementing multiline input
