### ISSUE TITLE
Chat overview details incorrect sorting / not reactive

### ISSUE THREAD

**Issue by jessedvrs** [part-up/app#43]
The chat message preview (last chat message) and time label are not updated due to bad sorting / lack of reactiveness.

**Comment by ralphboeije** [comment]
And the ordering is now on last message send and/or received I guess? It should be like in WhatsApp, sort on last message received first and then on last message send.

**Comment by jessedvrs** [comment]
Okay, can you please create a new issue for this as it hasn't anything to do with this one? ;)

**Comment by ralphboeije** [comment]
check

**Comment by jessedvrs** [comment]
#59
