### ISSUE TITLE
App - Register popup

### ISSUE THREAD

**Issue by peterpeerdeman** [part-up/app#5]
<a href="https://github.com/peterpeerdeman"><img src="https://avatars.githubusercontent.com/u/685599?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [peterpeerdeman](https://github.com/peterpeerdeman)**
_Monday Apr 11, 2016 at 12:28 GMT_
_Originally opened as https://github.com/part-up/part-up/issues/357_

----

as an appuser I want to link to the register functionality on the part-up website using the in app browser

**Comment by ralphboeije** [comment]
Just discussed with @jessedvrs that we might better not use the in-app browser, because of the login issues and ocassional freezes.
