### ISSUE TITLE
White screen of Death on iOS

### ISSUE THREAD

**Issue by wouterd** [part-up/app#50]
A few times a day, when switching to the part-up app, it just shows a white screen and hangs. After killing the app and starting it again it works.
I'm on iOS 9.

**Comment by ralphboeije** [comment]
This happens quite often when you return to the app after some time through a push notification

![img_4585](https://cloud.githubusercontent.com/assets/14044235/16310763/20d2b84c-396e-11e6-828c-bfb1d7163fb4.PNG)

**Comment by jessedvrs** [comment]
could you please verify whether this is still a bug in 1.3.0?

**Comment by ralphboeije** [comment]
haven't seen it yet in 1.4.0. Let's close it for now and I'll keep an eye on it.
