### ISSUE TITLE
App - Login with e-mail + password

### ISSUE THREAD

**Issue by peterpeerdeman** [part-up/app#6]
<a href="https://github.com/peterpeerdeman"><img src="https://avatars.githubusercontent.com/u/685599?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [peterpeerdeman](https://github.com/peterpeerdeman)**
_Monday Apr 11, 2016 at 12:29 GMT_
_Originally opened as https://github.com/part-up/part-up/issues/358_

----

as an app user I want to be able to login with user and password

https://redpen.io/tbacf0cf98739303aa

**Comment by ralphboeije** [comment]
Test finding: login with e-mail of a FB/LI registered user gives: "Login failed for an unknown reason" error message. Should be like in webapp: "This e-mail address is already used for a Linked or Facebook login. Please try login in with one of those."
