### ISSUE TITLE
App - Cordova Facebook / Linkedin integratie

### ISSUE THREAD

**Issue by peterpeerdeman** [part-up/app#7]
<a href="https://github.com/peterpeerdeman"><img src="https://avatars.githubusercontent.com/u/685599?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [peterpeerdeman](https://github.com/peterpeerdeman)**
_Monday Apr 11, 2016 at 12:30 GMT_
_Originally opened as https://github.com/part-up/part-up/issues/359_

----

as an appuser I want to be able to login using facebook and linkedin

**Comment by ralphboeije** [comment]
Test finding, this works pretty ok, but still a bit rough around the edges. But maybe that's just in progress state and I am to early with testing. It shows the oauth url in the frontend and sometimes you have to click the "done" button in the footer to log in. Is it possible to use the LI/FB native apps to do login? That is less burdensome for the user.

**Comment by jessedvrs** [comment]
Agree. Had to move this optimisation to the next sprint.

**Comment by peterpeerdeman** [comment]
will create new story for native social plugin integration
