### ISSUE TITLE
Show image and document icon in messages in the app

### ISSUE THREAD

**Issue by ralphboeije** [part-up/app#84]
FE:
- [x] Make item link to source (safari for image, possibly open dropbox/gdrive apps if installed, otherwise safari)
- [x] Reuse file uploader helper and implement to render icon
- [x] create render icon template
- [x] Create render image template

BE: 
- [x] Publish image property on backend 

As an upper I want to see the images (thumbnail) and document icons in the app and want to be able to click them to view the contents.

**Comment by jessedvrs** [comment]
![slack for ios upload](https://cloud.githubusercontent.com/assets/5961598/18355091/5b584548-75e8-11e6-9129-38ba28ca2121.jpg)
