### ISSUE TITLE
Increase spacing around notification icon

### ISSUE THREAD

**Issue by ralphboeije** [part-up/app#88]
When receiving a new update, the app shows an orange dot next to the new updates. In the app, this orange dot can cover the chat overview or update overview. See screenshots.

![img_4569](https://cloud.githubusercontent.com/assets/14044235/16056295/2515c89a-3275-11e6-89b9-54fd853045fa.PNG)
![img_4570](https://cloud.githubusercontent.com/assets/14044235/16056294/2514e4a2-3275-11e6-8620-8b24853ae723.PNG)

**Comment by peterpeerdeman** [comment]
was fixed in recent commit by @jessedvrs
