### ISSUE TITLE
Show original author of the update

### ISSUE THREAD

**Issue by ralphboeije** [part-up/app#90]
When you receive a notification of a comment on an update, the update detail shows the profile image of the commenter and the update text in orange as a header. Underneath the original post is shown and below that the comment of the commenter. See screenshot

This is somewhat confusing as it now appears as if the commenter has also written the original post. @LifelyPim we need to think of a way to improve this. My first idea: add the name of the writer of the original post before the text of the post in bold. e.g. in this screenshot it would read:

**By Theuy Limpanont**
CHAT CHAT CHAT!! ....

![img_4580](https://cloud.githubusercontent.com/assets/14044235/16098398/07eb9a4a-3353-11e6-86b6-bd2d67e5e996.PNG)

**Comment by ralphboeije** [comment]
Should be as in design of redpen https://redpen.io/yte0b5f98b342a5bdb and like on https://part-up.com/partups/growth-hacking-4qciwADvNquozWqtx/updates/B9Eii8g2i2NCvwC8q

**Comment by jessedvrs** [comment]
Hey @ralphboeije the difference with the website is that the website does not have a "notification-detail" screen which is magically linked to a partup-update. The website always redirects to the most relevant page possible. When a notification in the app says "Jesse replied to a conversation you follow", the app just opens the detail view of the notification, titled "Jesse replied to a conversation you follow" and not "Jesse added a message".

**Comment by jessedvrs** [comment]
This particular case is not designed and how it currently works is as how I interpreted the case.

**Comment by jessedvrs** [comment]
Your proposal to clarify the contents by prepending the text with "By [Author]:" requires an extra data call, but it's fair enough. This is only the case for message-related updates right?

**Comment by ralphboeije** [comment]
@jessedvrs please discuss this with @LifelyPim as we have extensively discussed this together.

**Comment by jessedvrs** [comment]
Fixed in 1b495f21ebd07d40afae9d1f98ae1fd7c3cbd593
