### ISSUE TITLE
Blank screen after tapping notification

### ISSUE THREAD

**Issue by jessedvrs** [part-up/app#91]

**Comment by ralphboeije** [comment]
duplicate to #50 ?

**Comment by jessedvrs** [comment]
could you please verify whether this is still a bug in 1.3.0?

**Comment by wouterd** [comment]
Just got the bug again on the latest app version.

**Comment by ralphboeije** [comment]
It seems to be a general issue when coming back to the app from a notification. Sometimes it freezes, sometimes a blank screens appears (I now always see it disappear after a second or two).

**Comment by ralphboeije** [comment]
Maybe related to chat performance (see part-up repo sprint backlog)
