### ISSUE TITLE
no notification needed when you add a message to a chat yourself

### ISSUE THREAD

**Issue by ralphboeije** [part-up/app#95]
To reproduce
1. go to chat overview tab
2. Click a person to chat with and go to chat detail
3. post a message
4. go back to chat tab and see the orange notification dot appear

![img_4584](https://cloud.githubusercontent.com/assets/14044235/16310844/7618d840-396e-11e6-96ae-8d9dc1af2205.PNG)

**Comment by jessedvrs** [comment]
Fixed in da1cacf96e85b24780aca1484c2ac31c022bcb20
