### ISSUE TITLE
In 1.2.3 the notifications dot doesn't go away until you close the app

### ISSUE THREAD

**Issue by ralphboeije** [part-up/app#97]
7hrs ago. And I have already read the message 10 times ;-)

![img_4591](https://cloud.githubusercontent.com/assets/14044235/16311067/51aeb80c-396f-11e6-8ad8-93d92a85b62a.PNG)

**Comment by jessedvrs** [comment]
The actual problem here is misplacement of the orange dot. It's a CSS issue causing the orange dot to be displayed on the wrong chat. Fixed in ea259a8fd7fedf9c2b68ed69be8456f807efc614
